site_name: mapp Framework
site_description: Public documentation for mapp Framework
site_author: B&R Community

repo_url: https://github.com/br-automation-community/mapp-Framework

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand

nav:
    - Table of contents: 
      - mapp Framework: index.md
      - General Information: 
          - General Information: general/index.md
          - Introduction: general/introduction.md
          - System Requirements: general/system_requirement.md
          - Prerequisites: general/Prerequisities.md
          - Launching the Importer: general/launching.md
          - User Partion Handling: general/user_partition.md
          - Visualization Consideration: general/visualization_consideration.md
          - Version Information: 
            - Overview: general/Version_information/index.md 
            - Version 1.5: general/Version_information/version_1_5.md
            - Version 1.4: general/Version_information/version_1_4.md
            - Version 1.3: general/Version_information/version_1_3.md
            - Version 1.2: general/Version_information/version_1_2.md
            - Version 1.1: general/Version_information/version_1_1.md
            - Version 1.0: general/Version_information/version_1_0.md
      - mapp AlarmX:
          - Introduction & Features: alarmx/index.md
      - mapp Axis / Cockpit:
          - Introduction & Features: axis_cockpit/index.md
      - mapp Backup:
          - Introduction & Features: backup/index.md
      - mapp File:
          - Introduction & Features: file/index.md
      - mapp Recipe:
          - Introduction & Features: recipe/index.md
      - mapp UserX:
          - Introduction & Features: userx/index.md
      - mapp Audit:
          - Introduction & Features: audit/index.md
      - mapp Report:
          - Introduction & Features: report/index.md
      - mapp PackML:
          - Introduction & Features: packml/index.md